import type { Metadata } from "next";
import { Merriweather, Karla } from "next/font/google";
import "./globals.css";

const merriweather = Merriweather({
	variable: '--font-heading',
	subsets: ['latin'],
})

const karla = Karla({
  variable: "--font-body",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
		<html lang='en' suppressHydrationWarning>
			<body
				className={`${merriweather.variable} ${karla.variable} h-screen antialiased`}
			>
				{children}
			</body>
		</html>
	)
}
